// Mocks generated by Mockito 5.4.6 from annotations
// in demo_clean_archtechture_with_provider/test/unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:demo_clean_archtechture_with_provider/core/errors/failure.dart'
    as _i5;
import 'package:demo_clean_archtechture_with_provider/core/params/params.dart'
    as _i7;
import 'package:demo_clean_archtechture_with_provider/features/posts/domain/entities/post.dart'
    as _i6;
import 'package:demo_clean_archtechture_with_provider/features/posts/domain/repositories/post_repositories.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i3.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PostEntities>> getAPost({
    required _i7.PostParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAPost, [], {#params: params}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.PostEntities>>.value(
                  _FakeEither_0<_i5.Failure, _i6.PostEntities>(
                    this,
                    Invocation.method(#getAPost, [], {#params: params}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PostEntities>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PostEntities>>> getAllPost({
    required _i7.PostParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPost, [], {#params: params}),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.PostEntities>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.PostEntities>>(
                    this,
                    Invocation.method(#getAllPost, [], {#params: params}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.PostEntities>>>);
}
